<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="CreateDBAndSaveDataFromWebServer.WebForm1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 56%;
            background-color: #FF00FF;
        }
        .auto-style2 {
            width: 239px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <table class="auto-style1">
                <tr>
                    <td class="auto-style2">&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style2">
                        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:CompanyConnectionString %>" DeleteCommand="DELETE FROM [Employees] WHERE [eId] = @eId" InsertCommand="INSERT INTO [Employees] ([eId], [eName], [eAddress], [eSalary]) VALUES (@eId, @eName, @eAddress, @eSalary)" ProviderName="<%$ ConnectionStrings:CompanyConnectionString.ProviderName %>" SelectCommand="SELECT * FROM [Employees]" UpdateCommand="UPDATE [Employees] SET [eName] = @eName, [eAddress] = @eAddress, [eSalary] = @eSalary WHERE [eId] = @eId">
                            <DeleteParameters>
                                <asp:Parameter Name="eId" Type="Int32" />
                            </DeleteParameters>
                            <InsertParameters>
                                <asp:Parameter Name="eId" Type="Int32" />
                                <asp:Parameter Name="eName" Type="String" />
                                <asp:Parameter Name="eAddress" Type="String" />
                                <asp:Parameter Name="eSalary" Type="Decimal" />
                            </InsertParameters>
                            <UpdateParameters>
                                <asp:Parameter Name="eName" Type="String" />
                                <asp:Parameter Name="eAddress" Type="String" />
                                <asp:Parameter Name="eSalary" Type="Decimal" />
                                <asp:Parameter Name="eId" Type="Int32" />
                            </UpdateParameters>
                        </asp:SqlDataSource>
                    </td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style2">
                        <asp:DetailsView ID="DetailsView1" runat="server" AutoGenerateEditButton="True" AutoGenerateInsertButton="True" AutoGenerateRows="False" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CaptionAlign="Top" CellPadding="4" CellSpacing="2" DataKeyNames="eId" DataSourceID="SqlDataSource1" ForeColor="Black" Height="50px" Width="125px">
                            <EditRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                            <Fields>
                                <asp:BoundField DataField="eId" HeaderText="eId" ReadOnly="True" SortExpression="eId" />
                                <asp:BoundField DataField="eName" HeaderText="eName" SortExpression="eName" />
                                <asp:BoundField DataField="eAddress" HeaderText="eAddress" SortExpression="eAddress" />
                                <asp:BoundField DataField="eSalary" HeaderText="eSalary" SortExpression="eSalary" />
                            </Fields>
                            <FooterStyle BackColor="#CCCCCC" />
                            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                            <PagerSettings FirstPageText="First" LastPageText="Last" NextPageText="Next" PreviousPageText="Previous" />
                            <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
                            <RowStyle BackColor="White" />
                        </asp:DetailsView>
                    </td>
                    <td>
                        <asp:GridView ID="GridView1" runat="server" AllowCustomPaging="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2" DataKeyNames="eId" DataSourceID="SqlDataSource1" ForeColor="Black" PageIndex="3" TabIndex="10">
                            <Columns>
                                <asp:BoundField DataField="eId" HeaderText="eId" ReadOnly="True" SortExpression="eId" />
                                <asp:BoundField DataField="eName" HeaderText="eName" SortExpression="eName" />
                                <asp:BoundField DataField="eAddress" HeaderText="eAddress" SortExpression="eAddress" />
                                <asp:BoundField DataField="eSalary" HeaderText="eSalary" SortExpression="eSalary" />
                            </Columns>
                            <FooterStyle BackColor="#CCCCCC" />
                            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                            <PagerSettings FirstPageText="First" LastPageText="Last" Mode="NextPreviousFirstLast" NextPageText="Next" PreviousPageText="Privious" />
                            <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
                            <RowStyle BackColor="White" />
                            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                            <SortedAscendingCellStyle BackColor="#F1F1F1" />
                            <SortedAscendingHeaderStyle BackColor="#808080" />
                            <SortedDescendingCellStyle BackColor="#CAC9C9" />
                            <SortedDescendingHeaderStyle BackColor="#383838" />
                        </asp:GridView>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style2">&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style2">&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style2">&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style2">&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style2">&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style2">&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style2">&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
            </table>
        </div>
    </form>
</body>
</html>
