<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm2.aspx.cs" Inherits="FrontToVsToDB.WebForm2" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 92%;
            height: 240px;
            background-color: #00FFFF;
        }
        .auto-style2 {
            width: 541px;
        }
        .auto-style3 {
            width: 456px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <table class="auto-style1">
                <tr>
                    <td class="auto-style3">&nbsp;</td>
                    <td class="auto-style2">&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style3">&nbsp;</td>
                    <td class="auto-style2">
                        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:CompanyConnectionString %>" DeleteCommand="DELETE FROM [Employees] WHERE [eId] = @eId" InsertCommand="INSERT INTO [Employees] ([eId], [eName], [eAddress], [eSalary]) VALUES (@eId, @eName, @eAddress, @eSalary)" ProviderName="<%$ ConnectionStrings:CompanyConnectionString.ProviderName %>" SelectCommand="SELECT * FROM [Employees]" UpdateCommand="UPDATE [Employees] SET [eName] = @eName, [eAddress] = @eAddress, [eSalary] = @eSalary WHERE [eId] = @eId">
                            <DeleteParameters>
                                <asp:Parameter Name="eId" Type="Int32" />
                            </DeleteParameters>
                            <InsertParameters>
                                <asp:Parameter Name="eId" Type="Int32" />
                                <asp:Parameter Name="eName" Type="String" />
                                <asp:Parameter Name="eAddress" Type="String" />
                                <asp:Parameter Name="eSalary" Type="Decimal" />
                            </InsertParameters>
                            <UpdateParameters>
                                <asp:Parameter Name="eName" Type="String" />
                                <asp:Parameter Name="eAddress" Type="String" />
                                <asp:Parameter Name="eSalary" Type="Decimal" />
                                <asp:Parameter Name="eId" Type="Int32" />
                            </UpdateParameters>
                        </asp:SqlDataSource>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style3">&nbsp;</td>
                    <td class="auto-style2">&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style3">
                        <asp:DetailsView ID="DetailsView1" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateInsertButton="True" AutoGenerateRows="False" DataKeyNames="eId" DataSourceID="SqlDataSource1" Height="100px" PageIndex="3" Width="226px">
                            <Fields>
                                <asp:BoundField DataField="eId" HeaderText="eId" ReadOnly="True" SortExpression="eId" />
                                <asp:BoundField DataField="eName" HeaderText="eName" SortExpression="eName" />
                                <asp:BoundField DataField="eAddress" HeaderText="eAddress" SortExpression="eAddress" />
                                <asp:BoundField DataField="eSalary" HeaderText="eSalary" SortExpression="eSalary" />
                            </Fields>
                            <PagerSettings FirstPageText="First" LastPageText="Last" Mode="NextPreviousFirstLast" NextPageText="Next" PreviousPageText="Previous" />
                            <PagerStyle BorderStyle="Solid" BorderWidth="2px" />
                        </asp:DetailsView>
                    </td>
                    <td class="auto-style2">
                        <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2" DataKeyNames="eId" DataSourceID="SqlDataSource1" ForeColor="Black" PageSize="5">
                            <Columns>
                                <asp:BoundField DataField="eId" HeaderText="eId" ReadOnly="True" SortExpression="eId" />
                                <asp:BoundField DataField="eName" HeaderText="eName" SortExpression="eName" />
                                <asp:BoundField DataField="eAddress" HeaderText="eAddress" SortExpression="eAddress" />
                                <asp:BoundField DataField="eSalary" HeaderText="eSalary" SortExpression="eSalary" />
                            </Columns>
                            <FooterStyle BackColor="#CCCCCC" />
                            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                            <PagerSettings FirstPageText="First" LastPageText="Last" Mode="NextPreviousFirstLast" NextPageText="Next" PreviousPageText="Previous" />
                            <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
                            <RowStyle BackColor="White" />
                            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                            <SortedAscendingCellStyle BackColor="#F1F1F1" />
                            <SortedAscendingHeaderStyle BackColor="#808080" />
                            <SortedDescendingCellStyle BackColor="#CAC9C9" />
                            <SortedDescendingHeaderStyle BackColor="#383838" />
                        </asp:GridView>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style3">
                        <asp:FormView ID="FormView1" runat="server" AllowPaging="True" BackColor="LightGoldenrodYellow" BorderColor="Tan" BorderWidth="1px" CellPadding="2" DataKeyNames="eId" DataSourceID="SqlDataSource1" ForeColor="Black" PageIndex="10">
                            <EditItemTemplate>
                                eId:
                                <asp:Label ID="eIdLabel1" runat="server" Text='<%# Eval("eId") %>' />
                                <br />
                                eName:
                                <asp:TextBox ID="eNameTextBox" runat="server" Text='<%# Bind("eName") %>' />
                                <br />
                                eAddress:
                                <asp:TextBox ID="eAddressTextBox" runat="server" Text='<%# Bind("eAddress") %>' />
                                <br />
                                eSalary:
                                <asp:TextBox ID="eSalaryTextBox" runat="server" Text='<%# Bind("eSalary") %>' />
                                <br />
                                <asp:LinkButton ID="UpdateButton" runat="server" CausesValidation="True" CommandName="Update" Text="Update" />
                                &nbsp;<asp:LinkButton ID="UpdateCancelButton" runat="server" CausesValidation="False" CommandName="Cancel" Text="Cancel" />
                            </EditItemTemplate>
                            <EditRowStyle BackColor="DarkSlateBlue" ForeColor="GhostWhite" />
                            <FooterStyle BackColor="Tan" />
                            <HeaderStyle BackColor="Tan" Font-Bold="True" />
                            <InsertItemTemplate>
                                eId:
                                <asp:TextBox ID="eIdTextBox" runat="server" Text='<%# Bind("eId") %>' />
                                <br />
                                eName:
                                <asp:TextBox ID="eNameTextBox" runat="server" Text='<%# Bind("eName") %>' />
                                <br />
                                eAddress:
                                <asp:TextBox ID="eAddressTextBox" runat="server" Text='<%# Bind("eAddress") %>' />
                                <br />
                                eSalary:
                                <asp:TextBox ID="eSalaryTextBox" runat="server" Text='<%# Bind("eSalary") %>' />
                                <br />
                                <asp:LinkButton ID="InsertButton" runat="server" CausesValidation="True" CommandName="Insert" Text="Insert" />
                                &nbsp;<asp:LinkButton ID="InsertCancelButton" runat="server" CausesValidation="False" CommandName="Cancel" Text="Cancel" />
                            </InsertItemTemplate>
                            <ItemTemplate>
                                eId:
                                <asp:Label ID="eIdLabel" runat="server" Text='<%# Eval("eId") %>' />
                                <br />
                                eName:
                                <asp:Label ID="eNameLabel" runat="server" Text='<%# Bind("eName") %>' />
                                <br />
                                eAddress:
                                <asp:Label ID="eAddressLabel" runat="server" Text='<%# Bind("eAddress") %>' />
                                <br />
                                eSalary:
                                <asp:Label ID="eSalaryLabel" runat="server" Text='<%# Bind("eSalary") %>' />
                                <br />
                                <asp:LinkButton ID="EditButton" runat="server" CausesValidation="False" CommandName="Edit" Text="Edit" />
                                &nbsp;<asp:LinkButton ID="DeleteButton" runat="server" CausesValidation="False" CommandName="Delete" Text="Delete" />
                                &nbsp;<asp:LinkButton ID="NewButton" runat="server" CausesValidation="False" CommandName="New" Text="New" />
                            </ItemTemplate>
                            <PagerSettings FirstPageText="first" LastPageText="Last" NextPageText="next" PreviousPageText="Previous" />
                            <PagerStyle BackColor="PaleGoldenrod" ForeColor="DarkSlateBlue" HorizontalAlign="Center" />
                        </asp:FormView>
                    </td>
                    <td class="auto-style2">&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style3">&nbsp;</td>
                    <td class="auto-style2">&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style3">&nbsp;</td>
                    <td class="auto-style2">&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style3">&nbsp;</td>
                    <td class="auto-style2">&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style3">&nbsp;</td>
                    <td class="auto-style2">&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style3">&nbsp;</td>
                    <td class="auto-style2">&nbsp;</td>
                </tr>
            </table>
        </div>
    </form>
</body>
</html>
