//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BluePrintOnScaffolding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal_Bank_Details
    {
        public int pId { get; set; }
        public string Customar_Name { get; set; }
        public Nullable<long> Customar_Acc { get; set; }
        public Nullable<long> Customar_Addar_Num { get; set; }
        public string Customar_Village { get; set; }
        public string Customar_Father_Name { get; set; }
    }
}
