//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp14thJulyInsertDeletEdit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie_Detail
    {
        public int Slno { get; set; }
        public string Movie_Name { get; set; }
        public string Hero_Name { get; set; }
        public Nullable<int> Ticket_price { get; set; }
        public string Location_Name { get; set; }
        public Nullable<long> collections { get; set; }
    }
}
