//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sco.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int eId { get; set; }
        public string eName { get; set; }
        public string eAddress { get; set; }
        public decimal eSalary { get; set; }
    }
}
