//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudWork
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CompanyEntities : DbContext
    {
        public CompanyEntities()
            : base("name=CompanyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
    
        public virtual int prc_selectname(Nullable<int> eId, ObjectParameter eName)
        {
            var eIdParameter = eId.HasValue ?
                new ObjectParameter("eId", eId) :
                new ObjectParameter("eId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_selectname", eIdParameter, eName);
        }
    
        public virtual ObjectResult<prc_empselectall_Result> prc_empselectall()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_empselectall_Result>("prc_empselectall");
        }
    }
}
